version: "3.8"

services:
  titspack-mc:
    image: itzg/minecraft-server:latest
    container_name: titspack-mc
    ports:
      - 32768:25565
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.19.3"
      FORGEVERSION: "44.1.23"
      MEMORY: "16G"
      PACKWIZ_URL: "https://ellitedev.github.io/titspack/pack.toml"
      RCON_PASSWORD: "titspack"
      ENABLE_RCON: "true"
      ENABLE_ROLLING_LOGS: "true"
      USE_AIKAR_FLAGS: "true"
      # Server.properties stuff
      MOTD: "\\u00A7dTits Pack\\u00A7r \\u00A7oVersion 2.5.2\\u00A7r\\nChangelog\\:\\u00A7o\\u00A7n https\\://link.ellite.dev/titschange"
      DIFFICULTY: "normal"
      ICON: "https://ellitedev.github.io/titspack/self-host/tits.png"
      OVERRIDE_ICON: "true"
      MAX_PLAYERS: "4"
      MAX_WORLD_SIZE: "20010"
      SPAWN_PROTECTION: "0"
      PVP: "true"
      ALLOW_FLIGHT: "true"
      SERVER_NAME: "TitsPack"
      EXEC_DIRECTLY: "true"
      STOP_SERVER_ANNOUNCE_DELAY: "30"
      OVERRIDE_SERVER_PROPERTIES: "true"
    depends_on:
      titspack-restore-backup:
        condition: service_completed_successfully
    volumes:
      - /root/docker-stuff/titspack/data:/data
    
  # "init" container for titspack-mc to restore the data volume when empty    
  titspack-restore-backup:
    # Same image as titspack-mc, but any base image with bash and tar will work
    image: itzg/mc-backup
    container_name: titspack-restore-backup
    restart: no
    entrypoint: restore-tar-backup
    volumes:
      # Must be same mount as titspack-mc service, needs to be writable
      - /root/docker-stuff/titspack/data:/data
      # Must be same mount as backups service, but can be read-only
      - /root/docker-stuff/titspack/backups:/backups:ro
  titspack-backups:
    image: itzg/mc-backup
    container_name: titspack-backups
    depends_on:
      titspack-mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: titspack-mc
      RCON_PASSWORD: "titspack"
      # since this service waits for titspack-mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
    volumes:
      - /root/docker-stuff/titspack/data:/data:ro
      - /root/docker-stuff/titspack/backups:/backups