name = "TitsPack"
author = "ellitedev"
version = "2.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c350fdb2fd2c7dfbc3d26eb946346c309fa27fcdd4bcd639754caa3319a504b"

[versions]
forge = "44.1.23"
minecraft = "1.19.3"

[options]
acceptable-game-versions = []
