name = "TitsPack"
author = "ellitedev"
version = "2.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81d89bccafe0c4e578a03363b517795dfa7d232646519f77887102bdc075f0fd"

[versions]
forge = "44.1.23"
minecraft = "1.19.3"

[options]
acceptable-game-versions = []
