name = "TitsPack"
author = "ellitedev"
version = "2.2.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca081edccf466904d45eccfc79e12079172b296250c84d44af7a9f57d3f96300"

[versions]
forge = "44.1.23"
minecraft = "1.19.3"

[options]
acceptable-game-versions = []
