name = "TitsPack"
author = "ellitedev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a602113cec7acacb69cf1b1a06d6015440a8e7bcb8685799d1933d4bdae1e3a"

[versions]
forge = "44.1.23"
minecraft = "1.19.3"
