name = "TitsPack"
author = "ellitedev"
version = "2.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5030fe107a95c5022265eccbe8547fa1ecceeb5679f1bc708d867cc2b0da3a5"

[versions]
forge = "44.1.23"
minecraft = "1.19.3"

[options]
acceptable-game-versions = []
