name = "TitsPack"
author = "ellitedev"
version = "2.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "764322a133b74e096932ebb75ea3633945538ee659237afaf11e914d99886e94"

[versions]
forge = "44.1.23"
minecraft = "1.19.3"
