name = "TitsPack"
author = "ellitedev"
version = "2.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52941ec408634f814b2f271e5aa6c273656d005e7a90e3f544f4036c2e564ae2"

[versions]
forge = "44.1.23"
minecraft = "1.19.3"
