name = "TitsPack"
author = "ellitedev"
version = "2.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "258368c0195c3252cdaf910a534601e7ef0c2c1a2e6fb8c3fdb261a689dafeb7"

[versions]
forge = "44.1.23"
minecraft = "1.19.3"

[options]
acceptable-game-versions = []
