name = "TitsPack"
author = "ellitedev"
version = "2.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec69d0b18de622a6081af3232d848e7040d65e27a9f34aad155c100741ba11f6"

[versions]
forge = "44.1.23"
minecraft = "1.19.3"

[options]
acceptable-game-versions = []
